from __future__ import annotations

import asyncio
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from sqlmodel import Session, SQLModel, select

from app.models.db import Project, ProjectFile, ProjectFolder
from app.tools import registry
from app.tools import file_generators
from app.tools import office_documents
from app.tools.office_documents import (
    MANAGE_PROJECT_FOLDERS_TOOL_NAME,
    READ_PROJECT_FILE_TOOL_NAME,
    WRITE_PROJECT_OFFICE_DOCUMENT_TOOL_NAME,
)
from tests.test_database import create_test_engine, drop_all_tables


class OfficeDocumentsToolTestCase(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.uploads_dir = Path(self.temp_dir.name) / "uploads"
        self.generated_dir = self.uploads_dir / "generated"
        self.generated_dir.mkdir(parents=True, exist_ok=True)
        self.engine = create_test_engine()
        drop_all_tables(self.engine)
        SQLModel.metadata.create_all(self.engine)

    def tearDown(self):
        self.engine.dispose()
        self.temp_dir.cleanup()

    def _create_project(self) -> int:
        with Session(self.engine) as session:
            project = Project(name="Alpha", client="Client A")
            session.add(project)
            session.commit()
            session.refresh(project)
            return project.id

    def test_read_project_file_lists_and_reads_text_file(self):
        project_id = self._create_project()
        project_dir = self.uploads_dir / "projects" / str(project_id)
        project_dir.mkdir(parents=True, exist_ok=True)
        file_path = project_dir / "note.txt"
        file_path.write_text("Project office context", encoding="utf-8")

        with Session(self.engine) as session:
            session.add(
                ProjectFile(
                    project_id=project_id,
                    name="note.txt",
                    file_type="txt",
                    path=str(file_path.relative_to(self.uploads_dir)),
                    size_bytes=file_path.stat().st_size,
                    summary="Text note",
                )
            )
            session.commit()

        with patch.object(office_documents, "engine", self.engine), patch.object(
            office_documents,
            "UPLOADS_DIR",
            self.uploads_dir,
        ):
            listed = asyncio.run(
                registry.execute(
                    READ_PROJECT_FILE_TOOL_NAME,
                    {"project_id": project_id, "action": "list", "file_types": ["txt"]},
                )
            )
            read = asyncio.run(
                registry.execute(
                    READ_PROJECT_FILE_TOOL_NAME,
                    {"project_id": project_id, "action": "read", "file_name": "note.txt"},
                )
            )

        self.assertEqual(listed["status"], "success")
        self.assertEqual(listed["output"]["count"], 1)
        self.assertEqual(read["status"], "success")
        self.assertIn("Project office context", read["output"]["content"])

    def test_write_project_office_document_creates_project_docx(self):
        project_id = self._create_project()

        with patch.object(office_documents, "engine", self.engine), patch.object(
            office_documents,
            "UPLOADS_DIR",
            self.uploads_dir,
        ), patch.object(file_generators, "UPLOADS_DIR", self.uploads_dir), patch.object(
            file_generators,
            "GENERATED_DIR",
            self.generated_dir,
        ):
            created = asyncio.run(
                registry.execute(
                    WRITE_PROJECT_OFFICE_DOCUMENT_TOOL_NAME,
                    {
                        "project_id": project_id,
                        "file_type": "docx",
                        "file_name": "client-summary.docx",
                        "title": "Client Summary",
                        "sections": [
                            {
                                "heading": "Executive Summary",
                                "content": "The document was generated by the Office skill.",
                                "level": 1,
                            }
                        ],
                        "summary": "Client summary",
                    },
                )
            )

        self.assertEqual(created["status"], "success", created)
        self.assertEqual(created["output"]["file_type"], "docx")

        with Session(self.engine) as session:
            project_file = session.get(ProjectFile, created["output"]["id"])
            project = session.get(Project, project_id)

        self.assertIsNotNone(project_file)
        self.assertTrue((self.uploads_dir / project_file.path).is_file())
        self.assertTrue(project.memory_stale)

    def test_generated_document_auto_assigns_matching_folder(self):
        project_id = self._create_project()

        with patch.object(office_documents, "engine", self.engine), patch.object(
            office_documents,
            "UPLOADS_DIR",
            self.uploads_dir,
        ), patch.object(file_generators, "UPLOADS_DIR", self.uploads_dir), patch.object(
            file_generators,
            "GENERATED_DIR",
            self.generated_dir,
        ):
            created = asyncio.run(
                registry.execute(
                    WRITE_PROJECT_OFFICE_DOCUMENT_TOOL_NAME,
                    {
                        "project_id": project_id,
                        "file_type": "docx",
                        "file_name": "项目交付计划.docx",
                        "title": "项目交付计划",
                        "content": "本文件用于项目交付计划、会议安排和里程碑管理。",
                        "summary": "项目交付计划",
                    },
                )
            )

        self.assertEqual(created["status"], "success", created)
        with Session(self.engine) as session:
            project_file = session.get(ProjectFile, created["output"]["id"])
            folder = session.get(ProjectFolder, project_file.folder_id)

        self.assertEqual(folder.name, "项目交付文档")

    def test_manage_project_folders_creates_and_moves_file(self):
        project_id = self._create_project()
        project_dir = self.uploads_dir / "projects" / str(project_id)
        project_dir.mkdir(parents=True, exist_ok=True)
        file_path = project_dir / "proposal.docx"
        file_path.write_bytes(b"placeholder")

        with Session(self.engine) as session:
            project_file = ProjectFile(
                project_id=project_id,
                name="proposal.docx",
                file_type="docx",
                path=str(file_path.relative_to(self.uploads_dir)),
                size_bytes=file_path.stat().st_size,
                summary="Proposal",
            )
            session.add(project_file)
            session.commit()
            session.refresh(project_file)
            file_id = project_file.id

        with patch.object(office_documents, "engine", self.engine), patch.object(
            office_documents,
            "UPLOADS_DIR",
            self.uploads_dir,
        ):
            created_folder = asyncio.run(
                registry.execute(
                    MANAGE_PROJECT_FOLDERS_TOOL_NAME,
                    {"project_id": project_id, "action": "create", "new_name": "客户确认材料"},
                )
            )
            moved = asyncio.run(
                registry.execute(
                    MANAGE_PROJECT_FOLDERS_TOOL_NAME,
                    {
                        "project_id": project_id,
                        "action": "move_file",
                        "file_id": file_id,
                        "folder_name": "客户确认材料",
                    },
                )
            )

        self.assertEqual(created_folder["status"], "success", created_folder)
        self.assertEqual(moved["status"], "success", moved)
        with Session(self.engine) as session:
            project_file = session.get(ProjectFile, file_id)
            folder = session.get(ProjectFolder, project_file.folder_id)

        self.assertEqual(folder.name, "客户确认材料")


if __name__ == "__main__":
    unittest.main()
