export const PROJECT_NOTES_COPY = {
  zh: {
    emptyTitle: "请先从左侧选择文档",
    emptyDescription:
      "可以先生成咨询售前模板，或者新建一篇 Markdown 文档开始整理。",
    editPlaceholder: "在这里编辑 Markdown 文档……",
    previewEmpty: "预览区域",
    currentDocument: "当前文档",
    selectDocument: "请选择文档",
    unsavedChanges: "有未保存的修改",
    edit: "编辑",
    split: "分栏",
    preview: "预览",
    aiAssist: "AI 润色",
    save: "保存",
    moreActions: "更多操作",
    rename: "重命名",
    delete: "删除",
    heading: "咨询项目笔记",
    bootstrap: "咨询售前模板",
    newDocument: "新建文档",
    createInFolder: "在该文件夹中新建文档",
    noDocuments: "暂无文档",
    uncategorized: "未分组",
    noProjectDocuments: "还没有项目文档",
    emptySidebarDescription:
      "可以先生成咨询售前模板，快速得到结构化的项目笔记目录。",
    emptyAction: "创建咨询售前模板",
    createDocument: "新建文档",
    renameDocument: "重命名文档",
    createDocumentDescription: "为当前项目新增一篇 Markdown 文档。",
    renameDocumentDescription: "更新当前文档的名称。",
    documentName: "文档名称",
    documentNamePlaceholder: "例如：项目总览",
    cancel: "取消",
    create: "创建",
    deleteDocument: "删除文档",
    deleteDocumentConfirm: "确定要删除“{name}”吗？此操作不可撤销。",
    aiTitle: "AI 写作助手",
    aiDraftLabel: "草稿或补充说明",
    aiDraftPlaceholder: "输入补充要求，或留空以直接润色当前文档。",
    generate: "生成",
    generatedResult: "生成结果",
    generatedResultEmpty: "生成结果会显示在这里",
    replace: "替换当前内容",
    append: "追加到文档",
    saved: "文档已保存",
    saveFailed: "保存失败",
    templateCreated: "咨询售前模板已创建",
    templateCreatedAndCleaned: "模板已创建，并清理了重复目录",
    templateCreateFailed: "模板创建失败",
    documentCreated: "文档已创建",
    documentCreateFailed: "创建文档失败",
    documentRenamed: "文档已重命名",
    documentRenameFailed: "重命名文档失败",
    documentDeleted: "文档已删除",
    documentDeleteFailed: "删除文档失败",
    aiGenerationFailed: "AI 润色失败，请稍后重试",
    aiApplied: "已应用到当前文档",
  },
  en: {
    emptyTitle: "Choose a document from the left",
    emptyDescription:
      "Create the consulting pre-sales template or start a new Markdown document.",
    editPlaceholder: "Edit your Markdown document here...",
    previewEmpty: "Preview area",
    currentDocument: "Current Document",
    selectDocument: "Select a document",
    unsavedChanges: "Unsaved changes",
    edit: "Edit",
    split: "Split",
    preview: "Preview",
    aiAssist: "AI Assist",
    save: "Save",
    moreActions: "More actions",
    rename: "Rename",
    delete: "Delete",
    heading: "Consulting Project Docs",
    bootstrap: "Consulting Pre-sales",
    newDocument: "New document",
    createInFolder: "Create document in this folder",
    noDocuments: "No documents yet",
    uncategorized: "Uncategorized",
    noProjectDocuments: "No project documents yet",
    emptySidebarDescription:
      "Create the consulting pre-sales template to start with a structured notes tree.",
    emptyAction: "Create Consulting Pre-sales Template",
    createDocument: "Create Document",
    renameDocument: "Rename Document",
    createDocumentDescription:
      "Create a new Markdown document for this project.",
    renameDocumentDescription: "Update the name of the current document.",
    documentName: "Document name",
    documentNamePlaceholder: "For example: Project Overview",
    cancel: "Cancel",
    create: "Create",
    deleteDocument: "Delete Document",
    deleteDocumentConfirm: "Delete \"{name}\"? This action cannot be undone.",
    aiTitle: "AI Writing Assistant",
    aiDraftLabel: "Draft or instruction",
    aiDraftPlaceholder:
      "Add guidance here, or leave empty to polish the current document.",
    generate: "Generate",
    generatedResult: "Generated result",
    generatedResultEmpty: "The generated result will appear here",
    replace: "Replace",
    append: "Append",
    saved: "Document saved",
    saveFailed: "Failed to save",
    templateCreated: "Consulting pre-sales template created",
    templateCreatedAndCleaned: "Template created and duplicate folders cleaned",
    templateCreateFailed: "Failed to create template",
    documentCreated: "Document created",
    documentCreateFailed: "Failed to create document",
    documentRenamed: "Document renamed",
    documentRenameFailed: "Failed to rename document",
    documentDeleted: "Document deleted",
    documentDeleteFailed: "Failed to delete document",
    aiGenerationFailed: "AI generation failed, please try again",
    aiApplied: "Applied to current document",
  },
} as const;

export function getProjectNotesCopy(isZh: boolean) {
  return isZh ? PROJECT_NOTES_COPY.zh : PROJECT_NOTES_COPY.en;
}
