"""Agent loop — the unified streaming + tool-execution core.

Replaces the P1 → P2 → P3 cascade with a single ``while`` loop that mirrors
how Claude Code and similar agents drive a tool-using LLM:

    repeat within the configured per-turn budget:
        text, tool_calls = stream one LLM turn
        if no tool_calls: break
        for each tool_call: execute via tool_executor → tool_result
        append tool_results back into the messages list
        emit ``agent_step`` event

Behavioral contract preserved from the old pipeline:
    * tool_use JSON blocks are extracted from both native and mixed-text formats
    * truncation auto-continues once at step 0 when no tool was emitted
    * markdown inline-display text is streamed before tool execution returns
    * HITAS confirmation halts the loop and persists pending actions
    * SSE events emitted are a superset of what P1+P2+P3 emit today
"""
from __future__ import annotations

import asyncio
import json
import logging
import time
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Any

from app.routers.chat_schemas import SendMessageRequest
from app.services.agent_harness.context_budget import apply_context_budget
from app.services.context_builder.assembly import validate_context_assembly_request
from app.services.agent_harness.run_rollout import checkpoint_chat_rollout
from app.services.agent_harness.tool_scheduler import plan_tool_execution
from app.services.agent_harness.turn_budget import (
    BudgetKind,
    TurnBudgetExceeded,
    TurnBudgetLedger,
    await_with_turn_deadline,
    iter_with_turn_deadline,
    normalize_turn_budget_limits,
)
from app.services.agent_harness.turn_retry import decide_turn_retry, normalize_max_attempts
from app.services.agent_harness.tool_transcript import (
    normalize_planned_tool_calls,
    normalize_tool_transcript,
)
from app.services.agent_harness.tool_policy import PolicyDecision, evaluate_tool_policy
from app.services.agent_harness.tool_execution_record import tool_event_is_failure
from app.services.chat.agent_step import AgentStep, build_agent_step_event
from app.services.chat.product_run_events import (
    StepCompletedStatus,
    ToolProgressStatus,
    confirmation_required as _confirmation_required_event,
    ErrorCode,
    run_failed as _run_failed_event,
    step_completed as _step_completed_event,
    step_started as _step_started_event,
    text_delta as _text_delta_event,
    tool_progress as _tool_progress_event,
)
from app.services.chat.sse import iter_with_heartbeat, sse_event
from app.services.chat.state import ChatSessionState
from app.services.chat.tool_executor import execute_tool_with_policy
from app.services.chat.tool_repair import extract_tool_use_json_blocks
from app.services.chat.truncation import strip_truncation_marker
from app.services.chat_tools import (
    ChatRuntime,
    _strip_internal_tool_markers,
    _tool_start_progress_payload,
)
from app.tools.capabilities import tool_display_name

logger = logging.getLogger(__name__)

_CONTINUATION_PROMPT = (
    "请从上一条回复被截断的位置继续，补齐后续内容和关键论证。"
    "不要重复已经写过的内容，不要调用工具。"
)


# ----------------------------------------------------------------------
# Stream consumption — one LLM call → text + tool_calls
# ----------------------------------------------------------------------


@dataclass
class _StreamResult:
    """Aggregates produced while draining one LLM stream.

    Events are *yielded* live by ``_consume_stream``; these fields hold the
    end-of-turn rollup the caller needs (final text, planned tool calls,
    extended-thinking reasoning, and whether the output was truncated).
    """

    text: str = ""
    tool_calls: list[dict] = field(default_factory=list)
    reasoning: str = ""
    truncated: bool = False


async def _iter_model_stream_with_safe_retry(
    runtime: ChatRuntime,
    state: ChatSessionState,
    request_messages: list[dict],
    request_system: str,
    *,
    stream_label: str,
) -> AsyncIterator[str | dict]:
    """Yield one model stream with a fail-closed replay boundary.

    Heartbeats are generated by Aria and do not commit the provider response.
    Any string yielded by the provider — including reasoning/tool markers and
    even an empty provider event — does commit it. A later failure is surfaced
    instead of replayed, so already rendered text or planned tool calls can
    never be duplicated by automatic recovery.
    """

    max_attempts = normalize_max_attempts(getattr(runtime, "model_turn_max_attempts", 2))
    base_delay_ms = int(getattr(runtime, "model_turn_retry_base_delay_ms", 500))
    max_delay_ms = int(getattr(runtime, "model_turn_retry_max_delay_ms", 5_000))
    response_committed = False

    for attempt in range(1, max_attempts + 1):
        try:
            source = runtime.llm.stream_response(
                request_messages,
                system=request_system,
                model=runtime.selected_model,
                tools=runtime.tools,
                max_tokens=runtime.max_tokens,
                temperature=runtime.temperature,
            )
            stream = iter_with_heartbeat(
                source,
                stage="thinking",
                # Same text as the initial frontend state to avoid flicker.
                message="Aria 正在思考...",
            )
            budget = state.turn_budget
            if isinstance(budget, TurnBudgetLedger):
                stream = iter_with_turn_deadline(
                    stream,
                    budget,
                    phase=stream_label,
                )
            async for item in stream:
                if not isinstance(item, dict):
                    response_committed = True
                yield item
            return
        except TurnBudgetExceeded:
            # A shared turn deadline is terminal. Replaying the model stream
            # would violate the same deadline and could duplicate committed
            # text/tool plans.
            raise
        except Exception as exc:
            decision = decide_turn_retry(
                exc,
                attempt=attempt,
                max_attempts=max_attempts,
                response_committed=response_committed,
                base_delay_ms=base_delay_ms,
                max_delay_ms=max_delay_ms,
            )
            trace_payload = decision.to_trace_dict()
            if not decision.retryable:
                event_type = (
                    "model_turn_retry_suppressed"
                    if decision.response_committed
                    else "model_turn_retry_exhausted"
                    if decision.reason == "attempts_exhausted"
                    else "model_turn_retry_not_allowed"
                )
                state.record_trace_event(event_type, stage=stream_label, **trace_payload)
                logger.warning(
                    "[model-turn] retry stopped stage=%s attempt=%s/%s "
                    "category=%s reason=%s committed=%s error_type=%s",
                    stream_label,
                    attempt,
                    max_attempts,
                    decision.category.value,
                    decision.reason,
                    decision.response_committed,
                    type(exc).__name__,
                )
                raise

            state.record_trace_event(
                "model_turn_retry_scheduled",
                stage=stream_label,
                next_attempt=attempt + 1,
                **trace_payload,
            )
            state.stage_timings["model_retry_count"] = int(
                state.stage_timings.get("model_retry_count", 0) or 0
            ) + 1
            state.stage_timings["model_retry_wait_ms"] = int(
                state.stage_timings.get("model_retry_wait_ms", 0) or 0
            ) + decision.delay_ms
            logger.warning(
                "[model-turn] safe retry stage=%s attempt=%s/%s delay_ms=%s category=%s reason=%s error_type=%s",
                stream_label,
                attempt,
                max_attempts,
                decision.delay_ms,
                decision.category.value,
                decision.reason,
                type(exc).__name__,
            )
            yield {
                "type": "status",
                "stage": "model_retry",
                "message": (
                    "模型服务暂时不可用，正在安全重试"
                    f"（{attempt}/{max_attempts - 1}）..."
                ),
                "attempt": attempt,
                "max_retries": max_attempts - 1,
                "delay_ms": decision.delay_ms,
            }
            retry_wait = asyncio.sleep(decision.delay_ms / 1_000)
            if isinstance(state.turn_budget, TurnBudgetLedger):
                await await_with_turn_deadline(
                    retry_wait,
                    state.turn_budget,
                    phase=f"{stream_label}_retry_wait",
                )
            else:
                await retry_wait


async def _consume_stream(
    runtime: ChatRuntime,
    state: ChatSessionState,
    messages: list[dict],
    *,
    step_index: int,
    stream_label: str,
    result: _StreamResult,
) -> AsyncIterator[str]:
    """Drain a single ``stream_response`` call, yielding SSE frames as they arrive.

    Text deltas, heartbeats and status frames are yielded the moment the model
    produces them, so the frontend renders the reply progressively instead of in
    one burst at end-of-turn. User-visible text, planned tool calls, reasoning
    and the truncation flag are accumulated into ``result`` for the caller.
    """
    started_at = time.perf_counter()
    transcript = normalize_tool_transcript(messages)
    request_messages = transcript.messages
    request_system = runtime.system
    if transcript.changed:
        metrics = transcript.metrics()
        state.record_trace_event(
            "tool_transcript_normalized",
            stage=stream_label,
            **metrics,
        )
        logger.warning(
            "[tool-transcript] normalized stage=%s issues=%s synthetic=%s orphans=%s",
            stream_label,
            metrics["issue_codes"],
            metrics["synthetic_result_count"],
            metrics["removed_orphan_count"],
        )

    context_window_tokens = int(getattr(runtime, "context_window_tokens", 0) or 0)
    if context_window_tokens > 0:
        budgeted = apply_context_budget(
            system=request_system,
            messages=request_messages,
            tools=runtime.tools,
            context_window_tokens=context_window_tokens,
            max_output_tokens=runtime.max_tokens,
            safety_margin_percent=int(
                getattr(runtime, "context_safety_margin_percent", 8) or 8
            ),
            history_summary_tokens=int(
                getattr(runtime, "context_history_summary_tokens", 1_024) or 1_024
            ),
        )
        request_system = budgeted.system
        request_messages = budgeted.messages
        budget_metrics = budgeted.report.to_dict()
        state.record_trace_event(
            "turn_context_budget",
            stage=stream_label,
            **budget_metrics,
        )
        if budgeted.report.compacted:
            logger.info(
                "[context-budget] compacted stage=%s before=%s after=%s messages=%s->%s tool_batches=%s->%s",
                stream_label,
                budgeted.report.estimated_total_before,
                budgeted.report.estimated_total_after,
                budgeted.report.history_messages_before,
                budgeted.report.history_messages_after,
                budgeted.report.tool_batches_before,
                budgeted.report.tool_batches_after,
            )

        # Compaction must retain the same call/result invariants as the input.
        # Normalize again as a fail-closed guard and trace any unexpected repair.
        post_budget_transcript = normalize_tool_transcript(request_messages)
        request_messages = post_budget_transcript.messages
        if post_budget_transcript.changed:
            state.record_trace_event(
                "post_budget_tool_transcript_normalized",
                stage=stream_label,
                **post_budget_transcript.metrics(),
            )
            logger.error(
                "[context-budget] repaired tool transcript after compaction stage=%s issues=%s",
                stream_label,
                [issue.code for issue in post_budget_transcript.issues],
            )

    # The manifest is bound to the exact initial provider request after both
    # transcript normalization and budgeting. Later steps intentionally append
    # tool call/results and receive their own turn_context_budget trace.
    context_manifest = getattr(runtime, "context_manifest", None)
    if context_manifest and step_index == 0 and stream_label == "step_0":
        context_valid, context_reason = validate_context_assembly_request(
            context_manifest,
            system=request_system,
            messages=request_messages,
            tools=runtime.tools,
        )
        if not context_valid:
            state.record_trace_event(
                "context_assembly_request_rejected",
                stage="before_model_request",
                reason=context_reason,
            )
            raise RuntimeError(f"context assembly request rejected: {context_reason}")

    async for item in _iter_model_stream_with_safe_retry(
        runtime,
        state,
        request_messages,
        request_system,
        stream_label=stream_label,
    ):
        if isinstance(item, dict):
            yield sse_event(item)
            continue

        chunk: str = item
        if not state.first_model_event_recorded:
            state.first_model_event_recorded = True
            state.stage_timings["model_first_event_ms"] = round((time.perf_counter() - started_at) * 1000)
            yield sse_event(
                {
                    "type": "timing",
                    "key": "model_first_event_ms",
                    "duration_ms": state.stage_timings["model_first_event_ms"],
                }
            )

        chunk, was_truncated = strip_truncation_marker(chunk)
        if was_truncated:
            result.truncated = True
            yield sse_event(
                {
                    "type": "status",
                    "stage": "continuing",
                    "message": "模型输出较长，已触发长度上限，正在尝试继续生成...",
                }
            )
            if not chunk:
                continue

        stripped = chunk.strip()

        # Internal "[TOOL_START:name]" progress marker
        if stripped.startswith("[TOOL_START:") and stripped.endswith("]"):
            tool_name = stripped[12:-1]
            evaluation = evaluate_tool_policy(runtime.action_policy, tool_name, {})
            if not evaluation.may_plan:
                state.record_trace_event(
                    "tool_marker_suppressed",
                    stage=stream_label,
                    tool_name=tool_name,
                    reason=evaluation.reason,
                    required_policy=evaluation.required_policy.value,
                    current_policy=str(getattr(runtime.action_policy, "value", runtime.action_policy)),
                )
                continue
            progress = _tool_start_progress_payload(tool_name)
            if progress:
                yield sse_event({"type": "tool_executing", "tool_name": tool_name, **progress})
            # v1 tool_progress(running) is emitted around the real tool
            # execution below (so it fires exactly once per tool call,
            # regardless of whether the model emits a [TOOL_START] marker).
            continue

        chunk = _strip_internal_tool_markers(chunk)
        if not chunk:
            continue
        stripped = chunk.strip()

        # Mixed-text tool_use JSON blocks
        mixed, cleaned = extract_tool_use_json_blocks(chunk)
        if mixed:
            for block in mixed:
                if _accept_tool_block(runtime, state, block, stream_label, source="text"):
                    result.tool_calls.append(block)
                    yield sse_event(
                        {
                            "type": "status",
                            "stage": "tool_planned",
                            "message": f"模型已规划调用工具：{block.get('name')}",
                        }
                    )
            if cleaned:
                result.text += cleaned
                yield sse_event({"type": "text", "content": cleaned})
                if state.run_id:
                    yield sse_event(_text_delta_event(state.run_id, cleaned))
            continue

        # Pure JSON tool_use / reasoning_content envelope
        if stripped.startswith("{") and stripped.endswith("}") and '"type"' in stripped:
            try:
                block = json.loads(stripped)
            except json.JSONDecodeError:
                block = None
            if isinstance(block, dict):
                if block.get("type") == "tool_use":
                    if _accept_tool_block(runtime, state, block, stream_label, source="json"):
                        result.tool_calls.append(block)
                        yield sse_event(
                            {
                                "type": "status",
                                "stage": "tool_planned",
                                "message": f"模型已规划调用工具：{block.get('name')}",
                            }
                        )
                    continue
                if block.get("type") == "reasoning_content":
                    result.reasoning += str(block.get("content") or "")
                    continue

        result.text += chunk
        yield sse_event({"type": "text", "content": chunk})
        if state.run_id:
            yield sse_event(_text_delta_event(state.run_id, chunk))


def _classify_tool_outcome_status(outcome: Any) -> str:
    """Map a tool ``ToolOutcome`` to a Product Run Event v1 tool_progress status.

    Reads the JSON-encoded ``content`` of the ``tool_result`` block fed back to
    the LLM. Any explicit error / success=False / status="error|failed" signal
    classifies the call as ``failed``; everything else (incl. unparseable
    payloads, since the tool clearly ran without raising) is ``completed``.
    """
    content_str = ""
    result_block = getattr(outcome, "result_block", None)
    if isinstance(result_block, dict):
        content_str = str(result_block.get("content") or "")
    try:
        payload = json.loads(content_str) if content_str else {}
    except (json.JSONDecodeError, TypeError):
        payload = {}
    if isinstance(payload, dict):
        if payload.get("error"):
            return ToolProgressStatus.FAILED
        if payload.get("success") is False or payload.get("ok") is False:
            return ToolProgressStatus.FAILED
        status_text = str(payload.get("status") or "").lower()
        if status_text in {"error", "failed"}:
            return ToolProgressStatus.FAILED
    return ToolProgressStatus.COMPLETED


def _accept_tool_block(
    runtime: ChatRuntime,
    state: ChatSessionState,
    block: dict,
    stream_label: str,
    *,
    source: str,
) -> bool:
    """Run the policy gate on a tool_use block. Record trace events on rejection."""
    name = str(block.get("name") or "")
    raw_input = block.get("input") if isinstance(block.get("input"), dict) else {}
    evaluation = evaluate_tool_policy(runtime.action_policy, name, raw_input)
    if evaluation.decision is PolicyDecision.FORBIDDEN:
        if source == "text":
            state.record_tool_use_via_text(stream_label, block, status="blocked")
        state.record_trace_event(
            "tool_blocked",
            stage=stream_label,
            tool_name=name,
            reason=evaluation.reason,
            required_policy=evaluation.required_policy.value,
            current_policy=str(getattr(runtime.action_policy, "value", runtime.action_policy)),
        )
        return False
    if source == "text":
        state.record_tool_use_via_text(stream_label, block, status="planned")
    return True


# ----------------------------------------------------------------------
# Message construction helpers
# ----------------------------------------------------------------------


def _build_assistant_message(text: str, tool_calls: list[dict], reasoning: str) -> dict:
    """Compose the assistant message dict to append to the LLM history."""
    content: list[dict] = []
    if text.strip():
        content.append({"type": "text", "text": text.strip()})
    for tc in tool_calls:
        content.append(
            {
                "type": "tool_use",
                "id": str(tc.get("id") or ""),
                "name": str(tc.get("name") or ""),
                "input": tc.get("input") or {},
            }
        )
    msg: dict[str, Any] = {"role": "assistant", "content": content}
    if reasoning:
        msg["reasoning_content"] = reasoning
    return msg


def _skipped_pending_result_block(tool_call: dict) -> dict:
    """Construct a synthetic tool_result for tool calls skipped after confirmation gate."""
    payload = {
        "ok": False,
        "success": False,
        "skipped": True,
        "status": "pending_confirmation",
        "reason": "前一个工具调用需要用户确认，本次未执行。",
    }
    return {
        "type": "tool_result",
        "tool_use_id": str(tool_call.get("id") or ""),
        "content": json.dumps(payload, ensure_ascii=False),
    }


def _append_text(existing: str, addition: str) -> str:
    if not addition:
        return existing
    if not existing:
        return addition
    return f"{existing.rstrip()}\n\n{addition}".strip()


def _checkpoint_step(state: ChatSessionState, step: AgentStep) -> None:
    if not state.rollout_task_id or state.rollout_bind is None:
        return
    try:
        checkpoint_chat_rollout(
            state.rollout_bind,
            state.rollout_task_id,
            step,
            state,
        )
    except Exception as exc:
        logger.warning("[rollout] failed to persist step checkpoint: %s", exc)
        state.record_trace_event(
            "rollout_checkpoint_failed",
            stage=f"step_{step.index}",
            error=str(exc)[:500],
        )


_PARALLEL_TOOL_STATE_LIST_FIELDS = (
    "pending_tool_confirmations",
    "pending_tool_actions",
    "trace_events",
    "artifacts",
    "pending_markdown_saves",
)


def _fork_parallel_tool_state(parent: ChatSessionState) -> ChatSessionState:
    """Create an isolated accumulator for one parallel-safe read call."""

    return ChatSessionState(
        run_id=parent.run_id,
        assistant_message_id=parent.assistant_message_id,
        stream_started_at=parent.stream_started_at,
    )


def _merge_parallel_tool_state(parent: ChatSessionState, child: ChatSessionState) -> None:
    """Merge one completed read call in original model-call order."""

    for event in child.tool_call_events:
        if isinstance(event, dict):
            parent.record_tool_execution(event)
    for field_name in _PARALLEL_TOOL_STATE_LIST_FIELDS:
        getattr(parent, field_name).extend(getattr(child, field_name))
    parent.confirmation_requested = parent.confirmation_requested or child.confirmation_requested
    parent.durable_task_completed = parent.durable_task_completed or child.durable_task_completed


# ----------------------------------------------------------------------
# Public entry point
# ----------------------------------------------------------------------


async def _run_agent_loop_impl(
    runtime: ChatRuntime,
    req: SendMessageRequest,
    state: ChatSessionState,
    budget: TurnBudgetLedger,
) -> AsyncIterator[str]:
    """Drive the LLM through the configured number of bounded tool turns.

    On exit the following ``state`` fields are populated for the persist step:

    * ``state.full_text``                  — concatenated user-visible text
    * ``state.steps``                      — per-iteration audit records
    * ``state.tool_call_events``           — UI summary of every tool execution
    * ``state.tool_result_blocks``         — last batch fed back to the LLM
    * ``state.artifacts``                  — collected via tool_executor
    * ``state.pending_markdown_saves``     — collected via tool_executor
    * ``state.pending_tool_actions``       — HITAS rows to persist
    * ``state.pending_tool_confirmations`` — frontend confirmation cards
    * ``state.confirmation_requested``     — early-exit signal for persist
    * ``state.trace_events``               — diagnostic stream
    """
    messages: list[dict] = list(runtime.api_messages)
    accumulated_text = ""
    workflow_announced = False
    loop_started_at = time.perf_counter()

    for step_index in range(budget.limits.max_steps):
        budget.start_step(phase=f"step_{step_index}")
        step = AgentStep(index=step_index)
        state.steps.append(step)
        step_started_at = time.perf_counter()

        # Product Run Event v1: open a step (1-based index; title is generic
        # because tool names aren't known until the model emits tool_use blocks).
        if state.run_id:
            yield sse_event(
                _step_started_event(state.run_id, step_index + 1, title=f"第 {step_index + 1} 步")
            )

        # ---------- one LLM turn (events stream out live as the model writes) ----------
        result = _StreamResult()
        try:
            async for ev in _consume_stream(
                runtime,
                state,
                messages,
                step_index=step_index,
                stream_label=f"step_{step_index}",
                result=result,
            ):
                yield ev
        finally:
            # Keep the text visible so far available to the outer interruption
            # boundary even when cancellation lands in the middle of a stream.
            step.model_text = result.text
            state.full_text = _append_text(accumulated_text, result.text)
        text = result.text
        tool_calls = result.tool_calls
        reasoning = result.reasoning
        truncated = result.truncated

        # ---------- truncation auto-continue (any step that ended on a cut-off
        # final answer, i.e. no tools emitted) ----------
        if truncated and not tool_calls and text.strip():
            cont_messages = messages + [
                {"role": "assistant", "content": text.strip()},
                {"role": "user", "content": _CONTINUATION_PROMPT},
            ]
            cont_result = _StreamResult()
            try:
                async for ev in _consume_stream(
                    runtime,
                    state,
                    cont_messages,
                    step_index=step_index,
                    stream_label=f"step_{step_index}_continuation",
                    result=cont_result,
                ):
                    yield ev
            finally:
                step.model_text = text + cont_result.text
                state.full_text = _append_text(accumulated_text, step.model_text)
            text += cont_result.text
            reasoning += cont_result.reasoning
            tool_calls.extend(cont_result.tool_calls)
            if cont_result.truncated:
                yield sse_event({"type": "truncated", "can_continue": True})
                truncated = True
            else:
                truncated = False
        elif truncated:
            # Truncated while still planning tools — no clean continuation path,
            # so surface it to the UI instead of auto-continuing.
            yield sse_event({"type": "truncated", "can_continue": True})

        planned_calls = normalize_planned_tool_calls(tool_calls, step_index=step_index)
        tool_calls = planned_calls.tool_calls
        if planned_calls.changed:
            state.record_trace_event(
                "planned_tool_calls_normalized",
                stage=f"step_{step_index}",
                **planned_calls.metrics(),
            )
            logger.warning(
                "[tool-transcript] normalized planned calls step=%s issues=%s removed_duplicates=%s",
                step_index,
                [issue.code for issue in planned_calls.issues],
                planned_calls.removed_duplicate_count,
            )

        step.model_text = text
        step.reasoning = reasoning
        step.truncated = truncated
        step.tool_calls = list(tool_calls)
        accumulated_text = _append_text(accumulated_text, text)
        state.full_text = accumulated_text

        if not tool_calls:
            step.duration_ms = round((time.perf_counter() - step_started_at) * 1000)
            step.status = "completed"
            _checkpoint_step(state, step)
            if state.run_id:
                yield sse_event(
                    _step_completed_event(
                        state.run_id,
                        step_index + 1,
                        StepCompletedStatus.COMPLETED,
                        step.duration_ms,
                        truncated=truncated,
                    )
                )
            break

        # Reserve the complete normalized batch before executing its first
        # call. This makes the limit atomic: an oversized plan performs none
        # of the newly planned calls.
        budget.reserve_tool_calls(
            len(tool_calls),
            phase=f"step_{step_index}_tools",
        )

        # ---------- mark workflow started once we know tools will run ----------
        # No canned "判断执行方式 / 准备参数" plan steps: the real tool executions
        # streamed below are the visible progress, matching the persisted view.
        if not workflow_announced:
            workflow_announced = True
            state.workflow_started = True

        # ---------- build assistant message + execute tools ----------
        messages.append(_build_assistant_message(text, tool_calls, reasoning))

        tool_result_blocks: list[dict] = []
        execution_plan = plan_tool_execution(
            tool_calls,
            action_policy=runtime.action_policy,
            max_parallel=getattr(runtime, "tool_parallel_max_concurrency", 4),
        )
        state.record_trace_event(
            "tool_execution_planned",
            stage=f"step_{step_index}",
            **execution_plan.to_trace_dict(),
        )
        confirmation_index: int | None = None

        for batch_number, batch in enumerate(execution_plan.batches, start=1):
            batch_started_at = time.perf_counter()
            indexed_calls = [(index, tool_calls[index]) for index in batch.indexes]

            # Emit every running event before a parallel batch begins. Terminal
            # events and model-visible results are still replayed in call order.
            for _, tool_call in indexed_calls:
                if state.run_id:
                    yield sse_event(
                        _tool_progress_event(
                            state.run_id,
                            step_index + 1,
                            title=tool_display_name(str(tool_call.get("name") or "")),
                            status=ToolProgressStatus.RUNNING,
                        )
                    )

            if batch.parallel:
                child_states = [_fork_parallel_tool_state(state) for _ in indexed_calls]
                outcomes = await await_with_turn_deadline(
                    asyncio.gather(
                        *(
                            execute_tool_with_policy(
                                runtime,
                                child_state,
                                tool_call,
                                req=req,
                                step_text=text,
                                step_truncated=truncated,
                                step_index=step_index,
                            )
                            for child_state, (_, tool_call) in zip(child_states, indexed_calls)
                        )
                    ),
                    budget,
                    phase=f"step_{step_index}_tool_batch_{batch_number}",
                    tool_execution_possible=True,
                )
                for child_state in child_states:
                    _merge_parallel_tool_state(state, child_state)
            else:
                _, tool_call = indexed_calls[0]
                outcomes = [
                    await await_with_turn_deadline(
                        execute_tool_with_policy(
                            runtime,
                            state,
                            tool_call,
                            req=req,
                            step_text=text,
                            step_truncated=truncated,
                            step_index=step_index,
                        ),
                        budget,
                        phase=f"step_{step_index}_tool_batch_{batch_number}",
                        tool_execution_possible=True,
                    )
                ]

            state.record_trace_event(
                "tool_execution_batch_completed",
                stage=f"step_{step_index}",
                batch_number=batch_number,
                lane=batch.lane.value,
                tool_count=len(indexed_calls),
                duration_ms=round((time.perf_counter() - batch_started_at) * 1000),
            )

            for (tc_index, tool_call), outcome in zip(indexed_calls, outcomes):
                for ev in outcome.events:
                    yield ev

                # Product Run Event v1: pair each tool with its terminal state.
                if state.run_id:
                    tool_name_v1 = str(tool_call.get("name") or "")
                    tool_title_v1 = tool_display_name(tool_name_v1)
                    if outcome.confirmation_required:
                        pending = (
                            state.pending_tool_confirmations[-1]
                            if state.pending_tool_confirmations
                            else {}
                        )
                        action_text = tool_display_name(
                            str(pending.get("tool_name") or tool_name_v1)
                        )
                        impact_text = (
                            str(pending.get("summary") or "")
                            or "该动作会修改或删除项目内容，需要用户确认才能继续。"
                        )
                        params_snapshot = (
                            pending.get("tool_input")
                            if isinstance(pending.get("tool_input"), dict)
                            else None
                        )
                        yield sse_event(
                            _confirmation_required_event(
                                state.run_id,
                                action=action_text,
                                impact=impact_text,
                                params_snapshot=params_snapshot,
                            )
                        )
                    else:
                        yield sse_event(
                            _tool_progress_event(
                                state.run_id,
                                step_index + 1,
                                title=tool_title_v1,
                                status=_classify_tool_outcome_status(outcome),
                            )
                        )

                # Markdown writes also stream their content as user-visible text.
                if outcome.markdown_inline_text:
                    accumulated_text = _append_text(accumulated_text, outcome.markdown_inline_text)
                    state.full_text = accumulated_text
                    yield sse_event({"type": "text", "content": outcome.markdown_inline_text})
                    if state.run_id:
                        yield sse_event(
                            _text_delta_event(state.run_id, outcome.markdown_inline_text)
                        )

                tool_result_blocks.append(outcome.result_block)
                if outcome.confirmation_required:
                    confirmation_index = tc_index
                    break

            if confirmation_index is not None:
                # Preserve transcript pairing for all calls behind the HITAS
                # barrier without executing them.
                for remaining in tool_calls[confirmation_index + 1 :]:
                    tool_result_blocks.append(_skipped_pending_result_block(remaining))
                break

        messages.append({"role": "user", "content": tool_result_blocks})
        state.tool_result_blocks = tool_result_blocks
        step.tool_results = tool_result_blocks
        step.duration_ms = round((time.perf_counter() - step_started_at) * 1000)
        step_events = [
            event
            for event in state.tool_call_events
            if isinstance(event, dict) and int(event.get("step_index", -1)) == step_index
        ]
        failed_events = [
            event
            for event in step_events
            if tool_event_is_failure(event)
        ]
        if confirmation_index is not None:
            step.status = "waiting_confirmation"
        elif failed_events:
            step.status = "failed"
            step.error = str(
                failed_events[-1].get("error")
                or failed_events[-1].get("summary")
                or "tool execution failed"
            )
            retry_candidates = [
                event
                for event in failed_events
                if str(event.get("status") or "") not in {"blocked", "conflict"}
            ]
            step.retryable = bool(retry_candidates) and all(
                bool(event.get("retryable", False)) for event in retry_candidates
            )
        else:
            step.status = "completed"
        step.retry_count = sum(
            max(0, int(event.get("attempt_count") or 1) - 1)
            for event in step_events
        )
        _checkpoint_step(state, step)

        yield sse_event(build_agent_step_event(step))
        if state.run_id:
            yield sse_event(
                _step_completed_event(
                    state.run_id,
                    step_index + 1,
                    (
                        StepCompletedStatus.FAILED
                        if step.status == "failed"
                        else StepCompletedStatus.COMPLETED
                    ),
                    step.duration_ms,
                    truncated=truncated,
                )
            )

        if state.confirmation_requested:
            break
    else:
        raise budget.step_limit_exceeded(phase="agent_loop")

    state.full_text = accumulated_text
    state.stage_timings["agent_loop_ms"] = round((time.perf_counter() - loop_started_at) * 1000)
    yield sse_event(
        {"type": "timing", "key": "agent_loop_ms", "duration_ms": state.stage_timings["agent_loop_ms"]}
    )


def _budget_exhaustion_notice(exc: TurnBudgetExceeded) -> str:
    if exc.kind is BudgetKind.STEP_LIMIT:
        return (
            f"本轮已达到 {int(exc.limit)} 步执行上限，已停止继续规划。"
            "已有内容和执行记录已保存，你可以发起新一轮继续。"
        )
    if exc.kind is BudgetKind.TOOL_CALL_LIMIT:
        return (
            f"本轮计划的工具调用超过 {int(exc.limit)} 次安全上限，"
            "超出部分未执行。已有内容和执行记录已保存。"
        )
    message = (
        f"本轮已达到 {float(exc.limit):g} 秒最长执行时间，已停止继续运行。"
        "已有内容和执行记录已保存。"
    )
    if exc.tool_execution_possible:
        message += "停止时工具可能已部分执行，请先核对实际结果再重试。"
    return message


async def run_agent_loop(
    runtime: ChatRuntime,
    req: SendMessageRequest,
    state: ChatSessionState,
) -> AsyncIterator[str]:
    """Run one Agent Loop behind a shared, persisted execution budget."""

    limits = normalize_turn_budget_limits(
        max_steps=getattr(runtime, "agent_turn_max_steps", 8),
        max_tool_calls=getattr(runtime, "agent_turn_max_tool_calls", 24),
        max_elapsed_seconds=getattr(runtime, "agent_turn_timeout_seconds", 600.0),
    )
    budget = TurnBudgetLedger(limits)
    state.turn_budget = budget
    loop_started_at = time.perf_counter()
    state.record_trace_event(
        "turn_budget_started",
        stage="agent_loop",
        **budget.snapshot(),
    )

    try:
        async for event in _run_agent_loop_impl(runtime, req, state, budget):
            yield event
    except TurnBudgetExceeded as exc:
        notice = _budget_exhaustion_notice(exc)
        state.budget_exhausted = True
        state.budget_exhaustion = {
            **exc.to_dict(),
            "message": notice,
            "budget": budget.snapshot(),
        }
        state.record_trace_event(
            "turn_budget_exhausted",
            **state.budget_exhaustion,
        )

        if state.steps and state.steps[-1].status == "running":
            step = state.steps[-1]
            step.status = "failed"
            step.error = str(exc)[:500]
            step.retryable = False
            _checkpoint_step(state, step)
            yield sse_event(build_agent_step_event(step))
            if state.run_id:
                yield sse_event(
                    _step_completed_event(
                        state.run_id,
                        step.index + 1,
                        StepCompletedStatus.FAILED,
                        step.duration_ms,
                        truncated=step.truncated,
                    )
                )

        state.full_text = _append_text(state.full_text, notice)
        state.stage_timings["agent_loop_ms"] = round(
            (time.perf_counter() - loop_started_at) * 1000
        )
        yield sse_event({"type": "text", "content": notice})
        if state.run_id:
            yield sse_event(_text_delta_event(state.run_id, notice))
            yield sse_event(
                _run_failed_event(
                    state.run_id,
                    ErrorCode.TURN_BUDGET_EXCEEDED,
                    notice,
                    retryable=False,
                    fallback_content=state.full_text,
                )
            )
        yield sse_event(
            {
                "type": "timing",
                "key": "agent_loop_ms",
                "duration_ms": state.stage_timings["agent_loop_ms"],
            }
        )
